# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Should only affect changes pushed to static_report directory, when merging to `main`

name: Node.js - Build & Commit to CLI data/report/**

on:
  pull_request:
    paths:
      - "static_report/**"
      # Trigger when diffs detected in statics source code
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./static_report

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: static_report/yarn.lock

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Prepare Piperider Data (2 runs; 1 comparison)
      working-directory: .
      run: |
        sudo apt-get install expect dejagnu
        mkdir -p ~/.piperider
        cat << EOF > ~/.piperider/profile.yml
        user_id: 00000000000000000000000000000000
        anonymous_tracking: true
        EOF
        pwd
        pip install -r requirements.txt
        which piperider
        piperider version
        runtest e2e-tests/testsuite/getting-started/001-run.exp
        runtest e2e-tests/testsuite/getting-started/002-compare.exp
        ls -a piperider-getting-started/.piperider/outputs
        ls -a piperider-getting-started/.piperider/comparisons
        
        echo "Piperider Data Generated. Ready for html embedding"

    - name: Install Dependencies
      run: yarn install --immutable

    - name: Cypress run (E2E)
    # Parallelization only for cypress dashboard https://www.cypress.io/pricing/
      uses: cypress-io/github-action@v2
      with:
        install: false
        working-directory: ./static_report
        config-file: cypress.config.ts
        build: npm run setup:e2e
        # change to `build apps`
        start: |
          npm run bundle:single
          npm run bundle:comparison
        wait-on: 'http://localhost:3000, http://localhost:3001' 

    - name: Build Apps
      run: npm run build

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: github.event.pull_request.merged == true
      with:
        commit_message: AUTO-COMMIT - build report statics to CLI data/report
        branch: ${{ github.base_ref }}
        # Auto-commits to target merge branch
